//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cabin
{
    public Cabin()
    {
        this.Passenger = new HashSet<Passenger>();
    }

    public int CabinID { get; set; }
    public string CabinDescription { get; set; }
    public Nullable<int> CabinPrice { get; set; }
    public Nullable<int> ClassID { get; set; }

    public virtual Class Class { get; set; }
    public virtual ICollection<Passenger> Passenger { get; set; }
}

public partial class Class
{
    public Class()
    {
        this.Cabin = new HashSet<Cabin>();
        this.Crew = new HashSet<Crew>();
    }

    public int ClassID { get; set; }
    public string ClassDescription { get; set; }

    public virtual ICollection<Cabin> Cabin { get; set; }
    public virtual ICollection<Crew> Crew { get; set; }
}

public partial class Crew
{
    public int CrewID { get; set; }
    public string Lastname { get; set; }
    public string Firstname { get; set; }
    public Nullable<int> Age { get; set; }
    public Nullable<int> DepartmentID { get; set; }
    public Nullable<int> CityID { get; set; }
    public string Job { get; set; }
    public Nullable<int> ClassID { get; set; }

    public virtual Class Class { get; set; }
    public virtual DepartCity DepartCity { get; set; }
    public virtual Department Department { get; set; }
}

public partial class DepartCity
{
    public DepartCity()
    {
        this.Crew = new HashSet<Crew>();
        this.Passenger = new HashSet<Passenger>();
    }

    public int cityID { get; set; }
    public string cityName { get; set; }

    public virtual ICollection<Crew> Crew { get; set; }
    public virtual ICollection<Passenger> Passenger { get; set; }
}

public partial class Department
{
    public Department()
    {
        this.Crew = new HashSet<Crew>();
    }

    public int DepartmentID { get; set; }
    public string DepartmentDescription { get; set; }

    public virtual ICollection<Crew> Crew { get; set; }
}

public partial class Passenger
{
    public int PassengerID { get; set; }
    public string Lastname { get; set; }
    public string Firstname { get; set; }
    public string Age { get; set; }
    public Nullable<int> CabinID { get; set; }
    public string Ticket { get; set; }
    public string TicketPrice { get; set; }
    public Nullable<int> CityID { get; set; }
    public string Job { get; set; }

    public virtual Cabin Cabin { get; set; }
    public virtual DepartCity DepartCity { get; set; }
}
